/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KindeManagementApi);
  }
}(this, function(expect, KindeManagementApi) {
  'use strict';

  var instance;
  
  const options = {
    domain: "test_domain",
    clientId: "test_client_id",
    clientSecret: "test_client_secret",
    redirectUri: "test_redirect_uri",
    logoutRedirectUri: "test_logout_redirect_uri",
    grantType: 'pkce',
  };

  beforeEach(function() {
    instance = new KindeManagementApi.KindeClient(options);
  });

  describe('KindeClient', function() {
    describe('constructor', function() {
      it('should initialize all properties', function(done) {
        //uncomment below and update the code to test constructor
        //expect(instance.domain).to.equal(options.domain);
        done();
      });
    });
    describe('login', function() {
      it('should call login successfully', function(done) {
        //uncomment below and update the code to test login
        //instance.login();
        //expect().to.be();
        done();
      });
    });
    describe('register', function() {
      it('should call register successfully', function(done) {
        //uncomment below and update the code to test register
        //instance.register();
        //expect().to.be();
        done();
      });
    });
    describe('callback', function() {
      it('should call callback successfully', function(done) {
        //uncomment below and update the code to test callback
        //instance.callback();
        //expect().to.be();
        done();
      });
    });
    describe('createOrg', function() {
      it('should call createOrg successfully', function(done) {
        //uncomment below and update the code to test createOrg
        //instance.createOrg();
        //expect().to.be();
        done();
      });
    });
    describe('logout', function() {
      it('should call logout successfully', function(done) {
        //uncomment below and update the code to test logout
        //instance.logout();
        //expect().to.be();
        done();
      });
    });
    describe('saveToken', function() {
      it('should call saveToken successfully', function(done) {
        //uncomment below and update the code to test saveToken
        //instance.saveToken(req, token);
        //expect().to.be();
        done();
      });
    });
    describe('cleanSession', function() {
      it('should call cleanSession successfully', function(done) {
        //uncomment below and update the code to test cleanSession
        //instance.cleanSession(req);
        //expect().to.be();
        done();
      });
    });
    describe('isAuthenticated', function() {
      it('should call isAuthenticated successfully', function(done) {
        //uncomment below and update the code to test isAuthenticated
        //instance.isAuthenticated(req);
        //expect().to.be();
        done();
      });
    });
    describe('getUserDetails', function() {
      it('should call getUserDetails successfully', function(done) {
        //uncomment below and update the code to test getUserDetails
        //instance.getUserDetails(req);
        //expect().to.be();
        done();
      });
    });
    describe('getClaims', function() {
      it('should call getClaims successfully', function(done) {
        //uncomment below and update the code to test getClaims
        //instance.getClaims(req);
        //expect().to.be();
        done();
      });
    });
    describe('getClaim', function() {
      it('should call getClaim successfully', function(done) {
        //uncomment below and update the code to test getClaim
        //instance.getClaim(req, 'given_name', 'id_token');
        //expect().to.be();
        done();
      });
    });
    describe('getPermissions', function() {
      it('should call getPermissions successfully', function(done) {
        //uncomment below and update the code to test getPermissions
        //instance.getPermissions(req);
        //expect().to.be();
        done();
      });
    });
    describe('getPermission', function() {
      it('should call getPermission successfully', function(done) {
        //uncomment below and update the code to test getPermission
        //instance.getPermission(req, 'create:todos');
        //expect().to.be();
        done();
      });
    });
    describe('getOrganization', function() {
      it('should call getOrganization successfully', function(done) {
        //uncomment below and update the code to test getOrganization
        //instance.getOrganization(req);
        //expect().to.be();
        done();
      });
    });
    describe('getUserOrganizations', function() {
      it('should call getUserOrganizations successfully', function(done) {
        //uncomment below and update the code to test getUserOrganizations
        //instance.getUserOrganizations(req);
        //expect().to.be();
        done();
      });
    });
  });

}));