/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */
import sinon from 'sinon';

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KindeManagementApi);
  }
}(this, function(expect, KindeManagementApi) {
  'use strict';

  var instance;
  beforeEach(function() {
    instance = new KindeManagementApi.RefreshToken();
  });

  describe('RefreshToken', function() {
    describe('getToken', async function() {
      let fetchStub;
      beforeEach(() => {
        fetchStub = sinon.stub(global, 'fetch');
      });
    
      afterEach(() => {
        fetchStub.restore();
      });

      it('should call getToken successfully', async () => {
        const client = {
          clientId: 'abc123',
          clientSecret: 'secret',
          redirectUri: 'https://example.com/redirect',
          tokenEndpoint: 'https://example.com/token',
          scope: 'scope',
          grantType: 'pkce',
        };
        const expectedSearchParams = new URLSearchParams({
          grant_type: 'refresh_token',
          client_id: client.clientId,
          client_secret: client.clientSecret,
          refresh_token: 'WvW8UFBtkSHMeWSdAGbj6QCpqe8FELC-5vgz9jAzKdI.RXLURfidYMuzCUN0lHN_JMxP-fIahw3BhxOSEUJudJQ',
        });
        const fakeToken = { access_token: '123456' };
        fetchStub.resolves({ json: sinon.stub().resolves(fakeToken) });
        const token = await instance.getToken(client, 'WvW8UFBtkSHMeWSdAGbj6QCpqe8FELC-5vgz9jAzKdI.RXLURfidYMuzCUN0lHN_JMxP-fIahw3BhxOSEUJudJQ');
        expect(fetchStub.calledOnce).to.be(true);
        expect(fetchStub.args[0][0]).to.be(client.tokenEndpoint);
        expect(fetchStub.args[0][1].method).to.be('POST');
        expect(fetchStub.args[0][1].headers['Content-Type']).to.be('application/x-www-form-urlencoded');
        expect(fetchStub.args[0][1].body.toString()).to.be(expectedSearchParams.toString());
        expect(token).to.eql(fakeToken);
      })
    });
  });
}));
