/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ConnectedAppsAuthUrl model module.
 * @module model/ConnectedAppsAuthUrl
 * @version 1
 */
class ConnectedAppsAuthUrl {
    /**
     * Constructs a new <code>ConnectedAppsAuthUrl</code>.
     * @alias module:model/ConnectedAppsAuthUrl
     */
    constructor() { 
        
        ConnectedAppsAuthUrl.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ConnectedAppsAuthUrl</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ConnectedAppsAuthUrl} obj Optional instance to populate.
     * @return {module:model/ConnectedAppsAuthUrl} The populated <code>ConnectedAppsAuthUrl</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ConnectedAppsAuthUrl();

            if (data.hasOwnProperty('url')) {
                obj['url'] = ApiClient.convertToType(data['url'], 'String');
            }
            if (data.hasOwnProperty('session_id')) {
                obj['session_id'] = ApiClient.convertToType(data['session_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ConnectedAppsAuthUrl</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ConnectedAppsAuthUrl</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['url'] && !(typeof data['url'] === 'string' || data['url'] instanceof String)) {
            throw new Error("Expected the field `url` to be a primitive type in the JSON string but got " + data['url']);
        }
        // ensure the json data is a string
        if (data['session_id'] && !(typeof data['session_id'] === 'string' || data['session_id'] instanceof String)) {
            throw new Error("Expected the field `session_id` to be a primitive type in the JSON string but got " + data['session_id']);
        }

        return true;
    }


}



/**
 * A URL that is used to authenticate an end-user against a connected app
 * @member {String} url
 */
ConnectedAppsAuthUrl.prototype['url'] = undefined;

/**
 * A unique identifier for the login session
 * @member {String} session_id
 */
ConnectedAppsAuthUrl.prototype['session_id'] = undefined;






export default ConnectedAppsAuthUrl;

