/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UserIdentity from './UserIdentity';

/**
 * The CreateUser200Response model module.
 * @module model/CreateUser200Response
 * @version 1
 */
class CreateUser200Response {
    /**
     * Constructs a new <code>CreateUser200Response</code>.
     * @alias module:model/CreateUser200Response
     */
    constructor() { 
        
        CreateUser200Response.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateUser200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUser200Response} obj Optional instance to populate.
     * @return {module:model/CreateUser200Response} The populated <code>CreateUser200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUser200Response();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Boolean');
            }
            if (data.hasOwnProperty('identities')) {
                obj['identities'] = ApiClient.convertToType(data['identities'], [UserIdentity]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateUser200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateUser200Response</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        if (data['identities']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['identities'])) {
                throw new Error("Expected the field `identities` to be an array in the JSON data but got " + data['identities']);
            }
            // validate the optional field `identities` (array)
            for (const item of data['identities']) {
                UserIdentity.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * Unique id of the user in Kinde
 * @member {String} id
 */
CreateUser200Response.prototype['id'] = undefined;

/**
 * True if the user was successfully created
 * @member {Boolean} created
 */
CreateUser200Response.prototype['created'] = undefined;

/**
 * @member {Array.<module:model/UserIdentity>} identities
 */
CreateUser200Response.prototype['identities'] = undefined;






export default CreateUser200Response;

