/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateOrganizationUserRoleRequest model module.
 * @module model/CreateOrganizationUserRoleRequest
 * @version 1
 */
class CreateOrganizationUserRoleRequest {
    /**
     * Constructs a new <code>CreateOrganizationUserRoleRequest</code>.
     * @alias module:model/CreateOrganizationUserRoleRequest
     */
    constructor() { 
        
        CreateOrganizationUserRoleRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateOrganizationUserRoleRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateOrganizationUserRoleRequest} obj Optional instance to populate.
     * @return {module:model/CreateOrganizationUserRoleRequest} The populated <code>CreateOrganizationUserRoleRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateOrganizationUserRoleRequest();

            if (data.hasOwnProperty('role_id')) {
                obj['role_id'] = ApiClient.convertToType(data['role_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateOrganizationUserRoleRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateOrganizationUserRoleRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['role_id'] && !(typeof data['role_id'] === 'string' || data['role_id'] instanceof String)) {
            throw new Error("Expected the field `role_id` to be a primitive type in the JSON string but got " + data['role_id']);
        }

        return true;
    }


}



/**
 * The role id.
 * @member {String} role_id
 */
CreateOrganizationUserRoleRequest.prototype['role_id'] = undefined;






export default CreateOrganizationUserRoleRequest;

