/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CreateUserRequestIdentitiesInner from './CreateUserRequestIdentitiesInner';
import CreateUserRequestProfile from './CreateUserRequestProfile';

/**
 * The CreateUserRequest model module.
 * @module model/CreateUserRequest
 * @version 1
 */
class CreateUserRequest {
    /**
     * Constructs a new <code>CreateUserRequest</code>.
     * @alias module:model/CreateUserRequest
     */
    constructor() { 
        
        CreateUserRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CreateUserRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateUserRequest} obj Optional instance to populate.
     * @return {module:model/CreateUserRequest} The populated <code>CreateUserRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateUserRequest();

            if (data.hasOwnProperty('profile')) {
                obj['profile'] = CreateUserRequestProfile.constructFromObject(data['profile']);
            }
            if (data.hasOwnProperty('identities')) {
                obj['identities'] = ApiClient.convertToType(data['identities'], [CreateUserRequestIdentitiesInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateUserRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateUserRequest</code>.
     */
    static validateJSON(data) {
        // validate the optional field `profile`
        if (data['profile']) { // data not null
          CreateUserRequestProfile.validateJSON(data['profile']);
        }
        if (data['identities']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['identities'])) {
                throw new Error("Expected the field `identities` to be an array in the JSON data but got " + data['identities']);
            }
            // validate the optional field `identities` (array)
            for (const item of data['identities']) {
                CreateUserRequestIdentitiesInner.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * @member {module:model/CreateUserRequestProfile} profile
 */
CreateUserRequest.prototype['profile'] = undefined;

/**
 * Array of identities to assign to the created user
 * @member {Array.<module:model/CreateUserRequestIdentitiesInner>} identities
 */
CreateUserRequest.prototype['identities'] = undefined;






export default CreateUserRequest;

