/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RedirectCallbackUrls model module.
 * @module model/RedirectCallbackUrls
 * @version 1
 */
class RedirectCallbackUrls {
    /**
     * Constructs a new <code>RedirectCallbackUrls</code>.
     * @alias module:model/RedirectCallbackUrls
     */
    constructor() { 
        
        RedirectCallbackUrls.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>RedirectCallbackUrls</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RedirectCallbackUrls} obj Optional instance to populate.
     * @return {module:model/RedirectCallbackUrls} The populated <code>RedirectCallbackUrls</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RedirectCallbackUrls();

            if (data.hasOwnProperty('redirect_urls')) {
                obj['redirect_urls'] = ApiClient.convertToType(data['redirect_urls'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RedirectCallbackUrls</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RedirectCallbackUrls</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['redirect_urls'])) {
            throw new Error("Expected the field `redirect_urls` to be an array in the JSON data but got " + data['redirect_urls']);
        }

        return true;
    }


}



/**
 * An application's redirect URLs.
 * @member {Array.<String>} redirect_urls
 */
RedirectCallbackUrls.prototype['redirect_urls'] = undefined;






export default RedirectCallbackUrls;

