/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateOrganizationUsersRequestUsersInner model module.
 * @module model/UpdateOrganizationUsersRequestUsersInner
 * @version 1
 */
class UpdateOrganizationUsersRequestUsersInner {
    /**
     * Constructs a new <code>UpdateOrganizationUsersRequestUsersInner</code>.
     * @alias module:model/UpdateOrganizationUsersRequestUsersInner
     */
    constructor() { 
        
        UpdateOrganizationUsersRequestUsersInner.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateOrganizationUsersRequestUsersInner</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateOrganizationUsersRequestUsersInner} obj Optional instance to populate.
     * @return {module:model/UpdateOrganizationUsersRequestUsersInner} The populated <code>UpdateOrganizationUsersRequestUsersInner</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateOrganizationUsersRequestUsersInner();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('operation')) {
                obj['operation'] = ApiClient.convertToType(data['operation'], 'String');
            }
            if (data.hasOwnProperty('roles')) {
                obj['roles'] = ApiClient.convertToType(data['roles'], ['String']);
            }
            if (data.hasOwnProperty('permissions')) {
                obj['permissions'] = ApiClient.convertToType(data['permissions'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateOrganizationUsersRequestUsersInner</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateOrganizationUsersRequestUsersInner</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['id'] && !(typeof data['id'] === 'string' || data['id'] instanceof String)) {
            throw new Error("Expected the field `id` to be a primitive type in the JSON string but got " + data['id']);
        }
        // ensure the json data is a string
        if (data['operation'] && !(typeof data['operation'] === 'string' || data['operation'] instanceof String)) {
            throw new Error("Expected the field `operation` to be a primitive type in the JSON string but got " + data['operation']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['roles'])) {
            throw new Error("Expected the field `roles` to be an array in the JSON data but got " + data['roles']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['permissions'])) {
            throw new Error("Expected the field `permissions` to be an array in the JSON data but got " + data['permissions']);
        }

        return true;
    }


}



/**
 * The users id.
 * @member {String} id
 */
UpdateOrganizationUsersRequestUsersInner.prototype['id'] = undefined;

/**
 * Optional operation, set to 'delete' to remove the user from the organization.
 * @member {String} operation
 */
UpdateOrganizationUsersRequestUsersInner.prototype['operation'] = undefined;

/**
 * Role keys to assign to the user.
 * @member {Array.<String>} roles
 */
UpdateOrganizationUsersRequestUsersInner.prototype['roles'] = undefined;

/**
 * Permission keys to assign to the user.
 * @member {Array.<String>} permissions
 */
UpdateOrganizationUsersRequestUsersInner.prototype['permissions'] = undefined;






export default UpdateOrganizationUsersRequestUsersInner;

