/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UpdateOrganizationUsersRequestUsersInner from './UpdateOrganizationUsersRequestUsersInner';

/**
 * The UpdateOrganizationUsersRequest model module.
 * @module model/UpdateOrganizationUsersRequest
 * @version 1
 */
class UpdateOrganizationUsersRequest {
    /**
     * Constructs a new <code>UpdateOrganizationUsersRequest</code>.
     * @alias module:model/UpdateOrganizationUsersRequest
     */
    constructor() { 
        
        UpdateOrganizationUsersRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UpdateOrganizationUsersRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateOrganizationUsersRequest} obj Optional instance to populate.
     * @return {module:model/UpdateOrganizationUsersRequest} The populated <code>UpdateOrganizationUsersRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateOrganizationUsersRequest();

            if (data.hasOwnProperty('users')) {
                obj['users'] = ApiClient.convertToType(data['users'], [UpdateOrganizationUsersRequestUsersInner]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>UpdateOrganizationUsersRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>UpdateOrganizationUsersRequest</code>.
     */
    static validateJSON(data) {
        if (data['users']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['users'])) {
                throw new Error("Expected the field `users` to be an array in the JSON data but got " + data['users']);
            }
            // validate the optional field `users` (array)
            for (const item of data['users']) {
                UpdateOrganizationUsersRequestUsersInner.validateJsonObject(item);
            };
        }

        return true;
    }


}



/**
 * Users to be added to the organization.
 * @member {Array.<module:model/UpdateOrganizationUsersRequestUsersInner>} users
 */
UpdateOrganizationUsersRequest.prototype['users'] = undefined;






export default UpdateOrganizationUsersRequest;

