/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponse from '../model/ErrorResponse';
import SuccessResponse from '../model/SuccessResponse';

/**
* FeatureFlags service.
* @module api/FeatureFlagsApi
* @version 1
*/
export default class FeatureFlagsApi {

    /**
    * Constructs a new FeatureFlagsApi. 
    * @alias module:api/FeatureFlagsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createFeatureFlag operation.
     * @callback module:api/FeatureFlagsApi~createFeatureFlagCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new feature flag
     * Create feature flag.
     * @param {String} name The name of the flag.
     * @param {String} description Description of the flag purpose.
     * @param {String} key The flag identifier to use in code.
     * @param {module:model/String} type The variable type.
     * @param {module:model/String} allowOverrideLevel Allow the flag to be overridden at a different level.
     * @param {String} defaultValue Default value for the flag used by environments and organizations.
     * @param {module:api/FeatureFlagsApi~createFeatureFlagCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SuccessResponse}
     */
    createFeatureFlag(name, description, key, type, allowOverrideLevel, defaultValue, callback) {
      let postBody = null;
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling createFeatureFlag");
      }
      // verify the required parameter 'description' is set
      if (description === undefined || description === null) {
        throw new Error("Missing the required parameter 'description' when calling createFeatureFlag");
      }
      // verify the required parameter 'key' is set
      if (key === undefined || key === null) {
        throw new Error("Missing the required parameter 'key' when calling createFeatureFlag");
      }
      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling createFeatureFlag");
      }
      // verify the required parameter 'allowOverrideLevel' is set
      if (allowOverrideLevel === undefined || allowOverrideLevel === null) {
        throw new Error("Missing the required parameter 'allowOverrideLevel' when calling createFeatureFlag");
      }
      // verify the required parameter 'defaultValue' is set
      if (defaultValue === undefined || defaultValue === null) {
        throw new Error("Missing the required parameter 'defaultValue' when calling createFeatureFlag");
      }

      let pathParams = {
      };
      let queryParams = {
        'name': name,
        'description': description,
        'key': key,
        'type': type,
        'allow_override_level': allowOverrideLevel,
        'default_value': defaultValue
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['kindeBearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json; charset=utf-8'];
      let returnType = SuccessResponse;
      return this.apiClient.callApi(
        '/api/v1/feature_flags', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteFeatureFlag operation.
     * @callback module:api/FeatureFlagsApi~deleteFeatureFlagCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a feature flag
     * Delete feature flag
     * @param {String} featureFlagKey The identifier for the feature flag.
     * @param {module:api/FeatureFlagsApi~deleteFeatureFlagCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SuccessResponse}
     */
    deleteFeatureFlag(featureFlagKey, callback) {
      let postBody = null;
      // verify the required parameter 'featureFlagKey' is set
      if (featureFlagKey === undefined || featureFlagKey === null) {
        throw new Error("Missing the required parameter 'featureFlagKey' when calling deleteFeatureFlag");
      }

      let pathParams = {
        'feature_flag_key': featureFlagKey
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['kindeBearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json; charset=utf-8'];
      let returnType = SuccessResponse;
      return this.apiClient.callApi(
        '/api/v1/feature_flags/{feature_flag_key}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateFeatureFlag operation.
     * @callback module:api/FeatureFlagsApi~updateFeatureFlagCallback
     * @param {String} error Error message, if any.
     * @param {module:model/SuccessResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a feature flag
     * Update feature flag.
     * @param {String} featureFlagKey The identifier for the feature flag.
     * @param {String} name The name of the flag.
     * @param {String} description Description of the flag purpose.
     * @param {String} key The flag identifier to use in code.
     * @param {module:model/String} type The variable type
     * @param {module:model/String} allowOverrideLevel Allow the flag to be overridden at a different level.
     * @param {String} defaultValue Default value for the flag used by environments and organizations.
     * @param {module:api/FeatureFlagsApi~updateFeatureFlagCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/SuccessResponse}
     */
    updateFeatureFlag(featureFlagKey, name, description, key, type, allowOverrideLevel, defaultValue, callback) {
      let postBody = null;
      // verify the required parameter 'featureFlagKey' is set
      if (featureFlagKey === undefined || featureFlagKey === null) {
        throw new Error("Missing the required parameter 'featureFlagKey' when calling updateFeatureFlag");
      }
      // verify the required parameter 'name' is set
      if (name === undefined || name === null) {
        throw new Error("Missing the required parameter 'name' when calling updateFeatureFlag");
      }
      // verify the required parameter 'description' is set
      if (description === undefined || description === null) {
        throw new Error("Missing the required parameter 'description' when calling updateFeatureFlag");
      }
      // verify the required parameter 'key' is set
      if (key === undefined || key === null) {
        throw new Error("Missing the required parameter 'key' when calling updateFeatureFlag");
      }
      // verify the required parameter 'type' is set
      if (type === undefined || type === null) {
        throw new Error("Missing the required parameter 'type' when calling updateFeatureFlag");
      }
      // verify the required parameter 'allowOverrideLevel' is set
      if (allowOverrideLevel === undefined || allowOverrideLevel === null) {
        throw new Error("Missing the required parameter 'allowOverrideLevel' when calling updateFeatureFlag");
      }
      // verify the required parameter 'defaultValue' is set
      if (defaultValue === undefined || defaultValue === null) {
        throw new Error("Missing the required parameter 'defaultValue' when calling updateFeatureFlag");
      }

      let pathParams = {
        'feature_flag_key': featureFlagKey
      };
      let queryParams = {
        'name': name,
        'description': description,
        'key': key,
        'type': type,
        'allow_override_level': allowOverrideLevel,
        'default_value': defaultValue
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['kindeBearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/json; charset=utf-8'];
      let returnType = SuccessResponse;
      return this.apiClient.callApi(
        '/api/v1/feature_flags/{feature_flag_key}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
