/**
 * Kinde Management API
 * Provides endpoints to manage your Kinde Businesses
 *
 * The version of the OpenAPI document: 1
 * Contact: support@kinde.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AuthorizationCode from './sdk/oauth2/AuthorizationCode';
import ClientCredentials from './sdk/oauth2/ClientCredentials';
import GrantType from './sdk/constant/GrantType';
import KindeClient from './KindeClient';
import PKCE from './sdk/oauth2/PKCE';
import RefreshToken from './sdk/oauth2/RefreshToken';
import AddOrganizationUsersRequest from './model/AddOrganizationUsersRequest';
import AddOrganizationUsersResponse from './model/AddOrganizationUsersResponse';
import ApiResult from './model/ApiResult';
import ConnectedAppsAccessToken from './model/ConnectedAppsAccessToken';
import ConnectedAppsAuthUrl from './model/ConnectedAppsAuthUrl';
import CreateOrganizationRequest from './model/CreateOrganizationRequest';
import CreateOrganizationResponse from './model/CreateOrganizationResponse';
import CreateUserRequest from './model/CreateUserRequest';
import CreateUserRequestIdentitiesInner from './model/CreateUserRequestIdentitiesInner';
import CreateUserRequestIdentitiesInnerDetails from './model/CreateUserRequestIdentitiesInnerDetails';
import CreateUserRequestProfile from './model/CreateUserRequestProfile';
import CreateUserResponse from './model/CreateUserResponse';
import Error from './model/Error';
import ErrorResponse from './model/ErrorResponse';
import GetOrganizationsResponse from './model/GetOrganizationsResponse';
import GetOrganizationsUsersResponse from './model/GetOrganizationsUsersResponse';
import Organization from './model/Organization';
import OrganizationUser from './model/OrganizationUser';
import RemoveOrganizationUsersRequest from './model/RemoveOrganizationUsersRequest';
import RemoveOrganizationUsersResponse from './model/RemoveOrganizationUsersResponse';
import SuccessResponse from './model/SuccessResponse';
import UpdateOrganizationRequest from './model/UpdateOrganizationRequest';
import UpdateUserRequest from './model/UpdateUserRequest';
import User from './model/User';
import UserIdentity from './model/UserIdentity';
import UserIdentityResult from './model/UserIdentityResult';
import UserProfile from './model/UserProfile';
import UserProfileV2 from './model/UserProfileV2';
import UsersResponse from './model/UsersResponse';
import ConnectedAppsApi from './api/ConnectedAppsApi';
import EnvironmentsApi from './api/EnvironmentsApi';
import FeatureFlagsApi from './api/FeatureFlagsApi';
import OAuthApi from './api/OAuthApi';
import OrganizationsApi from './api/OrganizationsApi';
import UsersApi from './api/UsersApi';


/**
* Provides endpoints to manage your Kinde Businesses.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var KindeManagementApi = require('index'); // See note below*.
* var xxxSvc = new KindeManagementApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new KindeManagementApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new KindeManagementApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new KindeManagementApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1
*/
export {    
    /**
     * The KindeClient class.
     * @property {class:KindeClient}
     */
    KindeClient,

    /**
     * The GrantType constant.
     * @property {const:GrantType}
     */
    GrantType,

    /**
     * The ClientCredentials class.
     * @property {class:ClientCredentials}
     */
    ClientCredentials,

    /**
     * The AuthorizationCode class.
     * @property {class:AuthorizationCode}
     */
    AuthorizationCode,

    /**
     * The PKCE class.
     * @property {class:PKCE}
     */
    PKCE,

    /**
     * The RefreshToken class.
     * @property {class:RefreshToken}
     */
    RefreshToken,

    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AddOrganizationUsersRequest model constructor.
     * @property {module:model/AddOrganizationUsersRequest}
     */
    AddOrganizationUsersRequest,

    /**
     * The AddOrganizationUsersResponse model constructor.
     * @property {module:model/AddOrganizationUsersResponse}
     */
    AddOrganizationUsersResponse,

    /**
     * The ApiResult model constructor.
     * @property {module:model/ApiResult}
     */
    ApiResult,

    /**
     * The ConnectedAppsAccessToken model constructor.
     * @property {module:model/ConnectedAppsAccessToken}
     */
    ConnectedAppsAccessToken,

    /**
     * The ConnectedAppsAuthUrl model constructor.
     * @property {module:model/ConnectedAppsAuthUrl}
     */
    ConnectedAppsAuthUrl,

    /**
     * The CreateOrganizationRequest model constructor.
     * @property {module:model/CreateOrganizationRequest}
     */
    CreateOrganizationRequest,

    /**
     * The CreateOrganizationResponse model constructor.
     * @property {module:model/CreateOrganizationResponse}
     */
    CreateOrganizationResponse,

    /**
     * The CreateUserRequest model constructor.
     * @property {module:model/CreateUserRequest}
     */
    CreateUserRequest,

    /**
     * The CreateUserRequestIdentitiesInner model constructor.
     * @property {module:model/CreateUserRequestIdentitiesInner}
     */
    CreateUserRequestIdentitiesInner,

    /**
     * The CreateUserRequestIdentitiesInnerDetails model constructor.
     * @property {module:model/CreateUserRequestIdentitiesInnerDetails}
     */
    CreateUserRequestIdentitiesInnerDetails,

    /**
     * The CreateUserRequestProfile model constructor.
     * @property {module:model/CreateUserRequestProfile}
     */
    CreateUserRequestProfile,

    /**
     * The CreateUserResponse model constructor.
     * @property {module:model/CreateUserResponse}
     */
    CreateUserResponse,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ErrorResponse model constructor.
     * @property {module:model/ErrorResponse}
     */
    ErrorResponse,

    /**
     * The GetOrganizationsResponse model constructor.
     * @property {module:model/GetOrganizationsResponse}
     */
    GetOrganizationsResponse,

    /**
     * The GetOrganizationsUsersResponse model constructor.
     * @property {module:model/GetOrganizationsUsersResponse}
     */
    GetOrganizationsUsersResponse,

    /**
     * The Organization model constructor.
     * @property {module:model/Organization}
     */
    Organization,

    /**
     * The OrganizationUser model constructor.
     * @property {module:model/OrganizationUser}
     */
    OrganizationUser,

    /**
     * The RemoveOrganizationUsersRequest model constructor.
     * @property {module:model/RemoveOrganizationUsersRequest}
     */
    RemoveOrganizationUsersRequest,

    /**
     * The RemoveOrganizationUsersResponse model constructor.
     * @property {module:model/RemoveOrganizationUsersResponse}
     */
    RemoveOrganizationUsersResponse,

    /**
     * The SuccessResponse model constructor.
     * @property {module:model/SuccessResponse}
     */
    SuccessResponse,

    /**
     * The UpdateOrganizationRequest model constructor.
     * @property {module:model/UpdateOrganizationRequest}
     */
    UpdateOrganizationRequest,

    /**
     * The UpdateUserRequest model constructor.
     * @property {module:model/UpdateUserRequest}
     */
    UpdateUserRequest,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
     * The UserIdentity model constructor.
     * @property {module:model/UserIdentity}
     */
    UserIdentity,

    /**
     * The UserIdentityResult model constructor.
     * @property {module:model/UserIdentityResult}
     */
    UserIdentityResult,

    /**
     * The UserProfile model constructor.
     * @property {module:model/UserProfile}
     */
    UserProfile,

    /**
     * The UserProfileV2 model constructor.
     * @property {module:model/UserProfileV2}
     */
    UserProfileV2,

    /**
     * The UsersResponse model constructor.
     * @property {module:model/UsersResponse}
     */
    UsersResponse,

    /**
    * The ConnectedAppsApi service constructor.
    * @property {module:api/ConnectedAppsApi}
    */
    ConnectedAppsApi,

    /**
    * The EnvironmentsApi service constructor.
    * @property {module:api/EnvironmentsApi}
    */
    EnvironmentsApi,

    /**
    * The FeatureFlagsApi service constructor.
    * @property {module:api/FeatureFlagsApi}
    */
    FeatureFlagsApi,

    /**
    * The OAuthApi service constructor.
    * @property {module:api/OAuthApi}
    */
    OAuthApi,

    /**
    * The OrganizationsApi service constructor.
    * @property {module:api/OrganizationsApi}
    */
    OrganizationsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};